### PR TITLE
Fix incompatible outlines

### PR DESCRIPTION
**Pull request by raphlinus**
This should fix the incompatible outlines as mentioned in #30. I'm starting to draft a few glyphs for additional weights, but it's best to do it on a solid foundation.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Thanks Raph. All glyphs are compatible in both sources.

It would be great to have just a single source file. Do we still need the non vf source? I'm pretty sure we can generate the statics just fine form the vf source.

**Comment by raphlinus** [comment]
> It would be great to have just a single source file. Do we still need the non vf source? I'm pretty sure we can generate the statics just fine form the vf source.

Sorry, somehow I missed seeing this comment until now. It's a good question. So far, I haven't done anything on the vf file that would preclude generating statics, but I plan to use it as something of a "development branch" (I just now uploaded my current work to the [four_weights](https://github.com/googlefonts/Inconsolata/tree/four_weights) branch). I'm not sure it will always be "green" (in that it will be possible to generate statics from it), especially as we shift our tooling.

So, to a large extent this is up to you:

* Keep the non-vf file around as the authoritative source for generating statics of 400 and 700 weights, and tread the vf file as the dev version, might be broken.

* Delete the non-vf file, and use best effort to maintain the vf file. If a release is needed, validate the current state and fix as needed.

**Comment by madig** [comment]
If you can generate a VF, you can generate statics, no?

**Comment by m4rc1e** [comment]
> Delete the non-vf file, and use best effort to maintain the vf file. If a release is needed, validate the current state and fix as needed.

I prefer this option. We'll need to check for regressions against the fonts on GF but it should be pretty good.

**Comment by raphlinus** [comment]
Ok, here's the state of play. I've been continuing to develop in the [two_axes2](https://github.com/googlefonts/Inconsolata/tree/two_axes2) branch, which now has ASCII in nine masters, but my workflow has diverged from being able to release a font from that glyphs file. The issue is that I've deleted the 700 normal-width master, so the bold is interpolated from 400 and 900. And the 900 is only valid in the ASCII range (outside that range, it's a copy of 700, which means it's not bold enough).

Thus, the same decision as listed above still presents:

* Less work for me, I could continue to develop the vf glyphs file without being concerned that the static instances are releasable from it. This is effectively a development branch.

* More work for me, but perhaps better for community involvement, I could do some scripting work to get it back to a releasable state, then delete the non-vf glyphs file. I believe what would get us there is *extrapolating* the 900 for the non-ASCII range, so that the process of interpolation would get us back to a state very similar to current master. Then I'd need to validate that.

I feel stuck on process and would like to get unstuck, particularly if there are other people who would like to contribute to getting the full character set ready.

**Comment by m4rc1e** [comment]
I've just had a look at the 9 master file and it's pretty cool.

Screenshot 2019-11-04 at 18 15 41

I'm very much in favour of the latter option but understand it's a tonne more work. @davelab6 perhaps a tvc next year can work on this with him?

**Comment by raphlinus** [comment]
Ok, I'll do the latter path, and it won't take me long. I just wanted to be sure the work is worth it.

Given that we've agreed on that, what's the strategy for getting this PR merged (especially as the two_axes2 branch is based on it)? Add a commit that deletes the non-vf glyphs file?

**Comment by raphlinus** [comment]
Ok, I've done the followup work, and it's in the [autofix](https://github.com/googlefonts/Inconsolata/tree/autofix) branch. I *believe* it would be possible to cut normal and bold instances, and those would be releasable, but I haven't (yet) done a careful audit. Basically, that branch has a placeholder auto-generated by affine transformation and lerping of the existing (400 and 700) masters. I believe getting that into master would improve the prospects for collaboration significantly, as the font is basically the final desired structure, it's just a question of improving the outlines so they don't look mechanically stretched.

So... what's the plan for getting all this merged?

**Comment by raphlinus** [comment]
Update: the autofix branch has some remaining master compatibility issues. A number of those are glyphs with smart corners (/Khook, /sixsuperior, /ninesuperior, /peseta), but also some arrows (/rightArrow, /upArrow, /northEastArrow). I seem to be able to trigger these compatibility issues when transforming through the Glyphs GUI as well, so still not sure what's causing it. My current strategy is to get these through by hook or by crook, then we can go forward.

**Comment by raphlinus** [comment]
And another update: the autofix branch now exports a variable TTF, and I've validated the resulting font lightly in wakamaifondue. So I'm not saying that there are no compatibility bugs, but I am saying they're probably minor and won't block progress on the font.

**Pull request merged**
